### ISSUE TITLE
Rename the branch

### ISSUE THREAD

**Issue by tackin** [freifunktrier/site-fftr#1]
Would like to suggest to rename the branch in something 2016.1.6 or so.

**Comment by basisbit** [comment]
I vote against that. Ideally there would only be the master branch + tags for the firmware releases

**Comment by tackin** [comment]
We talk about the active stable-build-branch, which is "2015.2" and not about the master.

**Comment by Ranlvor** [comment]
I wish that branch to be gone ASAP, the name doesn't matter.

**Comment by tackin** [comment]
As long as we rely on some cosmetic patches for just the actual gluon-builds we should not get rid of that branch. As master should always be able to build a stable without any additional patches. And because the patches in the branch 2015.2 are more or less for gluon 2016.1.6 we should refer this with its name.
