### ISSUE TITLE
Please add dns-cache to site.conf

### ISSUE THREAD

**Issue by pbriesch** [freifunktrier/site-fftr#8]
DNS-cache is possible in v2017.1.1.
Please add this to the site.conf.

http://gluon.readthedocs.io/en/v2017.1.x/features/dns-cache.html

**Comment by tackin** [comment]
Sorry, but does not make any sense in my eyes.
If you have any good reasons for this to have, please explain any reasonable benefit.

**Comment by pbriesch** [comment]
The benefits are explained in the documentation.

**Comment by tackin** [comment]
Well, I read the manual carefully, understand the details and could not find any benefit for us worth this discussion. Arguing with your words would help me to see if you understand, what you asked for.
Did you understand, that you don't have any IPv6 nor IPv4 in your Client without uplink, telling you that this DNS-Proxy is there? Do you understand any downside of having proxies behind our gateways?
We don't want any proxies in our net, as they are a pain in the ass in case of trouble. The trafficsaving of some packets on the other hand is redicolous less against this.

**Comment by basisbit** [comment]
I agree with @tackin, there is no need and rather more disadvantages than advantages in having the small and slow routers provide alternative DNS caching. At least, this is the case in such a network like theis one we are running as a community.
