### ISSUE TITLE
router.fftr not resolved anymore

### ISSUE THREAD

**Issue by pbriesch** [freifunktrier/site-fftr#9]
Very often during installations of nodes it is needed to know to which node a client is currently connected. By removing the below line router.fftr is not resolved any more and it is not possible to pull up the status page of the node by http://router.fftr

-- ip4 = '10.172.0.1', -- Segmentierung verhindert eindeutige next-node-IPv4

**Comment by tackin** [comment]
It still is, but only with IPv6.
take: http://[fd6a:2c55:3c00:9d0c::1]/ which will be also the resolved IPv6 if you call http://router.fftr .
No IPv4 available anymore cause of the segmentation-restrictions.

**Comment by pbriesch** [comment]
Well, it does not work currently. A ping6 does not work, either:

`PC192-168-4-105:~ pbriesch$ ping6 router.fftr
PING6(56=40+8+8 bytes) 2001:bf7:fc0f:2:55ba:1e75:bfde:215 --> fd6a:2c55:3c00:9d0c::1
^C
--- router.fftr ping6 statistics ---
265 packets transmitted, 0 packets received, 100.0% packet loss
PC192-168-4-105:~ pbriesch$`

**Comment by tackin** [comment]
It does. You might be connected with your Computer via LAN to your DSL and via WLAN on Freifunk. Pull out LAN and you will be ok.

**Comment by pbriesch** [comment]
Still doesn't work. Shouldn't the ping6 work?
